### PR TITLE
Add Hashable instance to URI

### PR DESCRIPTION
**Pull request by spacekitteh**

### CODE REVIEW

**Comment by mrkkrp** [comment]
Thanks! Can you also add a changelog entry?

**Comment by spacekitteh** [comment]
Done!

**Comment by mrkkrp** [comment]
Can you also fix formatting?

**Comment by spacekitteh** [comment]
Aight, done

**Comment by mrkkrp** [comment]
Looks like this is not building.

**Review by mrkkrp — APPROVED** [review]

**Comment by mrkkrp** [comment]
I've just published the version 0.3.5.0 on Hackage.

**Pull request merged**
