### PR TITLE
Percent encode delimiters and '@' that appear inside a PathPiece.

### PR DESCRIPTION
**Pull request by csasarak**
I'm suggesting this change to modify the instance of `RLabel` for  `PathPiece`s to not exclude delimiters or reserved characters within a `PathPiece` from being percent encoded.

I ran into an issue while trying to render a URI where one of the path components contained a `+` and also a `@`. These were excluded from percent encoding when rendering. Other parsers will sometimes fail to parse these URIs properly because they aren't expecting these reserved characters to appear in a path component.

For example:
```haskell
>>> uri = URI {uriScheme = Just "https", uriAuthority = Right (Authority {authUserInfo = Nothing, authHost = "foo.bar", authPort = Nothing}), uriPath = Just (False,"foo+bar@bar.com/baz" :| ["next-piece"]), uriQuery = [], uriFragment = Nothing}
>>> URI.render uri
```
Results in `"https://foo.bar/foo+bar@bar.com%2fbaz/next-piece"`, where some of the reserved characters are encoded but some are not. The result I would have expected is: `"https://foo.bar/foo%2bbar%40bar.com%2fbaz/next-piece"`.

The reason I think this PR is a improvement is that in the RFC [section 3.3](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) the final paragraph says that "Aside from dot-segments in hierarchical paths, a path segment is considered opaque by the generic syntax.". I take this to mean that reserved characters are allowed in path segments as long as they are percent encoded.

Thanks for making this library and for taking the time to review this PR, please let me know if I can clarify anything or if I've totally missed something in suggesting this change.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Can you please also update the changelog?

**Comment by mrkkrp** [comment]
I opened an issue regarding the CI failure: https://github.com/haskell/criterion/issues/258

**Comment by csasarak** [comment]
@mrkkrp Is `0.3.4.3` ok for the version? It seems unlikely, but I wonder if some consumers of this library may have been depending on the old behavior.

**Comment by mrkkrp** [comment]
Thanks! Applied as 7afb1cccbf36f1851dc907da0a744a6e82639a5a

**Comment by bmillwood** [comment]
I know I'm over a year late on this one, but FWIW I have encountered web resources in the wild that treat `@` and `%40` differently in path segments. My reading of the RFC is that they are explicitly permitted to treat them differently:

[section 2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2)
```
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.
```

I think the spec sort of exaggerates here: "most applications" will not change how they interpret a https URL based on whether it has `@` percent-encoded or not, but the fact remains that it seems *permissible* to do so.

...and therefore it should be possible to write a URI that renders with a real `@` in the path segment. I think the fact that you had to special-case `mailto` should perhaps be a prompt that there are other cases missing, too.

Happy to open a new issue if this seems worth more discussion.

**Pull request closed without merging**
