### PR TITLE
Support GHC 9.2

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by mrkkrp** [comment]
Installation of Cabal 3.6 seems to fail.

**Comment by sjakobi** [comment]
Indeed. Maybe the GHCup version is too old. Purging the cache might help?!

I probably won't debug this further. I can offer reverting the changes to `.github/workflows/ci.yaml`.

**Comment by mrkkrp** [comment]
I think 3.6 is simply not available in https://github.com/haskell/actions. Doesn't look to be the case:

https://github.com/haskell/actions/blob/main/setup/src/versions.json#L28

**Comment by sjakobi** [comment]
How about using `haskell-ci` for generating a GHA config?! `haskell-ci` does support GHC 9.2.1 and cabal 3.6.

**Comment by mrkkrp** [comment]
There seems to be so many different CI scripts now. Is `haskell-ci` considered better than `haskell/actions`? Does it support GitHub actions?

**Comment by sjakobi** [comment]
> Is `haskell-ci` considered better than `haskell/actions`? Does it support GitHub actions?

I have simply kept using `haskell-ci` since the Travis days. I haven't really bothered to learn how to configurate GHA myself.

I think it's pretty easy to use even though documentation is rather sparse. Options can be discovered via `haskell-ci --help` and should be added to `cabal.haskell-ci`. If you want to add CI with a different GHC version, add it to the `tested-with` section and run `haskell-ci regenerate`. Also, you should install `haskell-ci` from master. Hackage releases are done rather infrequently.

**Comment by sjakobi** [comment]
The `haskell-ci` maintainers are very responsive though. That's a plus for me. :)

**Review by sjakobi — COMMENTED** [review]
~~Looks like `bytestring`'s CI setup is going to have better architecture coverage than GHC! :muscle: ~~

Sorry, wrong PR! :blush:

**Comment by sjakobi** [comment]
Ping @mrkkrp. :)

**Comment by mrkkrp** [comment]
This is not forgotten. I plan to go over all my packages and update a bunch of things once mtl-2.3 is released. Which should happens tomorrow I guess?

**Comment by sjakobi** [comment]
> Which should happens tomorrow I guess?

Maybe. AFAIK the `mtl` maintainers need to decide whether the breaking changes included in rc-3 are acceptable first: https://github.com/haskell/mtl/issues/101#issuecomment-983766799

**Comment by mrkkrp** [comment]
Closing in favor of #45.

**Pull request closed without merging**
